# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DETALLE_EXPEDIENTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=2)),
                ('fase', models.CharField(max_length=2)),
                ('sec', models.IntegerField()),
                ('corr', models.IntegerField()),
                ('doc', models.CharField(max_length=40)),
                ('numero', models.CharField(max_length=40)),
                ('fecha', models.CharField(max_length=40)),
                ('ff', models.CharField(max_length=40)),
                ('moneda', models.CharField(max_length=10)),
                ('monto', models.FloatField()),
                ('est', models.CharField(max_length=40)),
                ('fechaProceso', models.CharField(max_length=40)),
                ('idTrx', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EXPEDIENTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('numeroEntidad', models.IntegerField()),
                ('descripcionEntidad', models.CharField(max_length=200)),
                ('expediente', models.IntegerField()),
                ('codigoTipoOperacion', models.CharField(max_length=40)),
                ('descripcionTipoOperacion', models.CharField(max_length=200)),
                ('codigoModalidadCompra', models.CharField(max_length=40)),
                ('descripcionModalidadCompra', models.CharField(max_length=200)),
                ('codigoTipoProcesoSeleccion', models.IntegerField()),
                ('descripcionTipoProceseoSeleccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='detalle_expediente',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captchas.EXPEDIENTE'),
        ),
    ]
