# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_expediente',
            name='ciclo',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_expediente',
            name='corr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle_expediente',
            name='doc',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_expediente',
            name='est',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_expediente',
            name='fase',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_expediente',
            name='fecha',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_expediente',
            name='fechaProceso',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_expediente',
            name='ff',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_expediente',
            name='idTrx',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_expediente',
            name='moneda',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_expediente',
            name='monto',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle_expediente',
            name='numero',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_expediente',
            name='sec',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='anio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='codigoModalidadCompra',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='codigoTipoOperacion',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='codigoTipoProcesoSeleccion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='descripcionEntidad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='descripcionModalidadCompra',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='descripcionTipoOperacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='descripcionTipoProceseoSeleccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='expediente',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numeroEntidad',
            field=models.IntegerField(null=True),
        ),
    ]
